name: agentic_ideation
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - pip
  - httpx=0.24.1
  - pyyaml=6.0
  - aiohttp=3.8.0
  - asyncio=3.4.3
  - pip:
    - python-dotenv>=1.0.0
    - pydantic>=2.0.0
    - colorlog>=6.7.0
    - tqdm>=4.65.0
    - aiofiles>=23.1.0
    - aiologger>=0.7.0
    - pytest-asyncio>=0.21.0  # For testing async code
    - pytest-aiohttp>=1.0.4   # For testing async HTTP
    - black>=23.0.0           # Code formatting
    - mypy>=1.0.0            # Type checking
