name: agentic_ideation
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - pip
  - httpx=0.24.1
  - pyyaml=6.0
  - pip:
    - python-dotenv>=1.0.0
    - pydantic>=2.0.0
    - colorlog>=6.7.0
    - tqdm>=4.65.0
