topic: "How might we engineer a plant based protein that reduces 50% sarcopenia in 6 months."

focus_levels:
  # Level 1: Primary Research Areas
  - level_name: "Primary Research Areas"
    focuses:
      - "protein engineering"
      - "clinical research"
      - "nutritional science"
      - "medical specialization"
      - "manufacturing"
      - "regulatory compliance"
      - "market analysis"
    num_agents: 20
    parent_focus: null

  # Level 2: Engineering Specifics
  - level_name: "Engineering Specifics"
    focuses:
      - "protein structure analysis"
      - "amino acid optimization"
      - "folding simulation"
      - "stability enhancement"
      - "bioavailability improvement"
    num_agents: 20
    parent_focus: "protein engineering"

  # Level 3: Engineering Deep Dive
  - level_name: "Engineering Deep Dive"
    focuses:
      - "molecular modeling"
      - "binding site optimization"
      - "protein-protein interactions"
      - "structural stability analysis"
      - "conformational dynamics"
    num_agents: 15
    parent_focus: "protein structure analysis"

  # Level 4: Clinical Details
  - level_name: "Clinical Details"
    focuses:
      - "efficacy testing"
      - "safety assessment"
      - "dosage optimization"
      - "absorption studies"
      - "side effect monitoring"
    num_agents: 15
    parent_focus: "clinical research"

  # Level 5: Clinical Deep Dive
  - level_name: "Clinical Deep Dive"
    focuses:
      - "muscle tissue response"
      - "protein uptake mechanisms"
      - "biomarker analysis"
      - "metabolic pathways"
      - "cellular signaling"
    num_agents: 10
    parent_focus: "efficacy testing"

  # Level 6: Nutritional Science Specifics
  - level_name: "Nutritional Science Specifics"
    focuses:
      - "protein bioavailability"
      - "amino acid profiling"
      - "nutrient synergies"
      - "digestibility analysis"
      - "nutritional requirements"
    num_agents: 15
    parent_focus: "nutritional science"

  # Level 7: Nutritional Deep Dive
  - level_name: "Nutritional Deep Dive"
    focuses:
      - "protein-nutrient interactions"
      - "absorption mechanisms"
      - "metabolic optimization"
      - "nutrient timing"
      - "supplementation strategies"
    num_agents: 10
    parent_focus: "protein bioavailability"

  # Level 8: Medical Specialization
  - level_name: "Medical Specialization"
    focuses:
      - "geriatric medicine"
      - "sports medicine"
      - "rehabilitation"
      - "endocrinology"
      - "muscle physiology"
    num_agents: 15
    parent_focus: "medical specialization"

  # Level 9: Medical Deep Dive
  - level_name: "Medical Deep Dive"
    focuses:
      - "sarcopenia mechanisms"
      - "muscle regeneration"
      - "hormone optimization"
      - "inflammation control"
      - "recovery protocols"
    num_agents: 10
    parent_focus: "geriatric medicine"

  # Level 10: Dietetic Implementation
  - level_name: "Dietetic Implementation"
    focuses:
      - "meal planning"
      - "dietary protocols"
      - "compliance strategies"
      - "progress monitoring"
      - "dietary adjustments"
    num_agents: 10
    parent_focus: "nutritional science"

  # Level 11: Production Specifics
  - level_name: "Production Specifics"
    focuses:
      - "scale-up process"
      - "quality control"
      - "cost optimization"
      - "equipment selection"
      - "batch validation"
    num_agents: 10
    parent_focus: "manufacturing"

  # Level 12: Manufacturing Deep Dive
  - level_name: "Manufacturing Deep Dive"
    focuses:
      - "process optimization"
      - "yield improvement"
      - "purification techniques"
      - "stability testing"
      - "contamination prevention"
    num_agents: 10
    parent_focus: "scale-up process"

  # Level 13: Regulatory Deep Dive
  - level_name: "Regulatory Deep Dive"
    focuses:
      - "safety documentation"
      - "clinical trial protocols"
      - "quality assurance"
      - "compliance monitoring"
      - "regulatory submissions"
    num_agents: 10
    parent_focus: "regulatory compliance"

  # Level 14: Market Intelligence
  - level_name: "Market Intelligence"
    focuses:
      - "competitor analysis"
      - "pricing strategy"
      - "distribution channels"
      - "customer segmentation"
      - "market positioning"
    num_agents: 10
    parent_focus: "market analysis"

  # Level 15: Implementation Strategy
  - level_name: "Implementation Strategy"
    focuses:
      - "production timeline"
      - "resource allocation"
      - "risk mitigation"
      - "quality metrics"
      - "success indicators"
    num_agents: 10
    parent_focus: null

# Deep Dive Configuration
deep_dive_agents:
  - level_name: "Deep Dive Analysis"
    agent_types:
      - name: "Pattern Analyzer"
        focus: "identify patterns and correlations"
        num_agents: 5
      - name: "Gap Investigator"
        focus: "identify research and implementation gaps"
        num_agents: 5
      - name: "Innovation Scout"
        focus: "identify breakthrough opportunities"
        num_agents: 5
      - name: "Risk Assessor"
        focus: "identify potential challenges and solutions"
        num_agents: 5
      - name: "Integration Specialist"
        focus: "identify cross-domain synergies"
        num_agents: 5

prompts:
  subtask_execution: "{persona}\nYour task: {subtask}\nConsider the following aspects:\n1. Current state analysis\n2. Improvement opportunities\n3. Implementation challenges\n4. Success metrics\n5. Next steps"
  synthesizer: "Topic: {topic}\nAnalyze the results focusing on:\n1. Key findings\n2. Critical insights\n3. Implementation recommendations\n4. Risk factors\n5. Success criteria"
