topic: "AI in Malaysia: Opportunity or Threat to the Future Workforce?"

focus_levels:
  # Level 1: Primary Research Areas
  - level_name: "Primary Research Areas"
    focuses:
      - "workforce impact analysis"
      - "economic implications"
      - "education and training"
      - "industry transformation"
      - "policy and regulation"
      - "social impact"
      - "technological readiness"
    num_agents: 20
    parent_focus: null

  # Level 2: Workforce Analysis
  - level_name: "Workforce Analysis"
    focuses:
      - "job displacement risk"
      - "new job creation"
      - "skill requirements"
      - "workforce adaptation"
      - "labor market trends"
    num_agents: 20
    parent_focus: "workforce impact analysis"

  # Level 3: Economic Impact
  - level_name: "Economic Impact"
    focuses:
      - "productivity analysis"
      - "industry competitiveness"
      - "investment patterns"
      - "economic growth potential"
      - "income distribution effects"
    num_agents: 15
    parent_focus: "economic implications"

  # Level 4: Education System
  - level_name: "Education System"
    focuses:
      - "curriculum adaptation"
      - "reskilling programs"
      - "digital literacy"
      - "industry partnerships"
      - "educational technology"
    num_agents: 15
    parent_focus: "education and training"

  # Level 5: Industry Sectors
  - level_name: "Industry Sectors"
    focuses:
      - "manufacturing automation"
      - "service sector AI adoption"
      - "tech startup ecosystem"
      - "traditional business transformation"
      - "digital infrastructure"
    num_agents: 15
    parent_focus: "industry transformation"

  # Level 6: Policy Framework
  - level_name: "Policy Framework"
    focuses:
      - "AI governance"
      - "labor protection"
      - "innovation incentives"
      - "data protection"
      - "ethical guidelines"
    num_agents: 15
    parent_focus: "policy and regulation"

analysis_agents:
  - level_name: "Impact Analysis"
    agent_types:
      - name: "Trend Analyzer"
        focus: "identify emerging patterns in workforce transformation"
        num_agents: 5
      - name: "Risk Assessor"
        focus: "evaluate potential threats and opportunities"
        num_agents: 5
      - name: "Policy Expert"
        focus: "analyze regulatory implications"
        num_agents: 5
      - name: "Economic Analyst"
        focus: "assess economic impact and opportunities"
        num_agents: 5
      - name: "Social Impact Evaluator"
        focus: "examine societal consequences"
        num_agents: 5

deep_dive_agents:
  - level_name: "Deep Dive Analysis"
    agent_types:
      - name: "Industry Specialist"
        focus: "sector-specific impact analysis"
        num_agents: 5
      - name: "Education Expert"
        focus: "skill development and training needs"
        num_agents: 5
      - name: "Technology Analyst"
        focus: "AI adoption and implementation patterns"
        num_agents: 5
      - name: "Labor Market Expert"
        focus: "employment trends and workforce dynamics"
        num_agents: 5
      - name: "Policy Researcher"
        focus: "regulatory framework analysis"
        num_agents: 5

synthesis_requirements:
  - "Identify key opportunities and threats"
  - "Analyze short-term vs long-term impacts"
  - "Evaluate readiness of Malaysian workforce"
  - "Assess policy implications"
  - "Recommend action steps for stakeholders"

prompts:
  subtask_execution: "{persona}\nYour task: {subtask}\nConsider the following aspects:\n1. Current state of AI adoption in Malaysia\n2. Workforce transformation opportunities\n3. Implementation challenges\n4. Success metrics\n5. Next steps"
  synthesizer: "Topic: {topic}\nAnalyze the results focusing on:\n1. Key findings on AI impact\n2. Critical insights for Malaysian workforce\n3. Implementation recommendations\n4. Risk mitigation strategies\n5. Success criteria for stakeholders"
